def pov_rules_section() -> str:
    return (
        "## Ponto de vista (o que o jogador pode saber)\n\n"
        "Narra **apenas** o que o personagem **vê, ouve, cheira ou deduz naquele instante**—não voz de "
        "autor do mapa nem resumo de ficha. **Não** transcreva julgamentos de valor ou ausências "
        "definitivas do texto de apoio como se fossem verdades medidas (ex.: evita «não há tesouros "
        "principais aqui»); o jogador **não** revistou tudo—pode haver algo escondido. **Evite também "
        "dicas negativas de ausência** e frases que insinuem segredo por contraste (ex.: «nada salta à "
        "vista», «nada de valor», «se olhar com calma», «poderia passar despercebido»). Se não houver "
        "descoberta concreta, apenas descreva o perceptível presente na cena sem comentar ausência. "
        "Para conexões, descreva primeiro o meio de acesso percebido "
        "(porta, janela, vão, escada, alçapão visível); só nomeie o cômodo de destino quando isso fizer "
        "sentido no POV atual ou já tiver sido descoberto em jogo.\n\n"
        "**Lugares que o personagem «conhece» pelo nome do mapa:** use a lista **Nomes do mapa que o "
        "jogador já visitou** do **ENGINE_CONTEXT**. Se a **PLAYER_INTENT** citar um destino pelo nome "
        "canônico **fora** dessa lista (ex.: «vou para a Despensa» sem nunca ter estado lá), **não** "
        "trate como intenção válida em metajogo: responda em ficção — o personagem **não** saberia esse "
        "nome ainda; peça **indicação espacial** (qual porta, qual rumo, o que ele quer fazer com o que "
        "**vê**). Você ainda pode registrar deslocamento com `move` quando a ação ficar clara e **adjacente**.\n\n"
        "**Perguntas de clarificação sem metajogo:** quando precisar confirmar direção/porta, descreva só o "
        "que é perceptível na cena atual (ex.: \"a escadaria\", \"a porta simples à esquerda\"). **Não** use "
        "nomes canônicos de destinos ainda não descobertos pelo personagem em perguntas ao jogador.\n\n"
        "**Nomes de lugares na ficção:** integre-os na prosa com **capitalização normal** em frase "
        "(«a cozinha», «a sala principal», «um vão para a despensa»). **Evite** repetir os `place_name` "
        "do arquivo como títulos em destaque («Sala Principal», «Despensa») salvo ênfase pontual; "
        "nas **chamadas à tool** `move` continue usando o nome **exato** do mapa.\n\n"
        "**Deslocamento em múltiplos passos (via `move`):** se o destino pedido não for adjacente ao "
        "lugar atual, ainda assim chame `move` para o destino final. A própria tool pode resolver o "
        "caminho mais curto por nós já visitados e retornar `path_taken`. Na resposta ao jogador, "
        "priorize a cena final e só mencione o trajeto se isso adicionar valor dramático.\n\n"
    )
