from app.config import NarratorPromptConfig
from app.narrator_prompt.section_scene_image_note import scene_image_instruction_paragraph
from tools.move import STARTING_PLACE_NAME


def tools_move_and_dice_section(config: NarratorPromptConfig) -> str:
    scene_image_note = scene_image_instruction_paragraph(config)
    return (
        "## Ferramentas\n\n"
        "Use **`move`** quando o jogador **for para outro lugar** do mapa (não para o lugar inicial "
        f"**{STARTING_PLACE_NAME}** enquanto ele não tiver saído dele): em `place_name` use o **nome "
        "canônico** do mapa. O jogador fala em linguagem natural («volto pro salão grande», «sala principal»): "
        "**você** traduz para o nome certo (ex.: **São Principal**) antes de chamar a tool; não exija que "
        "ele copie o dicionário.\n\n"
        "Ao narrar a **chegada** quando **`revisit`: false**, baseie-se **apenas** em **`basic_description`** "
        "e em `player_facing_summary` **e** nas **conexões** retornadas (objetos com `to`, `how` e "
        "sinalizadores de passagem). **Não** puxe para a prosa de chegada o que seria só da camada "
        "**`details`** (ainda não está no JSON). Com **`revisit`: true**, se vier **`details`**, pode "
        "aprofundar; em prosa, priorize o "
        "que é perceptível por `how` (porta, janela, vão, escada, treliça, etc.) como **âncoras "
        "espaciais**; não transforme em lista técnica. Trate `to` como referência de motor, não como "
        "fala obrigatória ao jogador, **mas** na chegada a um cômodo novo cite de forma natural "
        "**as saídas visíveis principais** (portas e passagens realmente transitáveis no `move`) para "
        "orientação do jogador. Quando houver 5 ou menos saídas visíveis, mencione todas "
        "mais imediatas no texto da chegada; se houver nomes canônicos claros (ex.: Despensa, São "
        "Principal), pode citar esses destinos junto com o `how` em linguagem diegética. Se o acesso "
        "parecer oculto/segredo ou não diretamente visível, "
        "não revele o destino nominal antes de exploração pertinente. Se a conexão sugerir obstáculo "
        "(ex.: `seems_traversable_now=false`, treliça sem passagem, janela só para ver), trate como "
        "**secundário** na lista mental do personagem: **não** equacione com porta ou passagem principal; "
        "pode ser um vão de luz ou vista, sem virar «via» como as saídas de fato. Descreva a limitação "
        "e **não valide deslocamento** por aí sem ação clara. Ao voltar texto do mapa em narração, **filtre** "
        "julgamentos de tesouro/valor ou ausências categóricas para a **voz do personagem** (ver "
        "**Regra dura de anti-vazamento na chegada:** em resposta de `move` (entrada em cômodo), "
        "**proibido** mencionar «abertura secreta», «passagem oculta/discreta», «quase imperceptível», "
        "«fenda estranha», «ventilação suspeita» ou qualquer formulação equivalente que sugira caminho "
        "escondido. Se não houve gatilho válido (ação direta no ponto certo ou `roll_dice` bem-sucedido), "
        "essas informações **não existem** na narração desse turno. "
        f"**Ponto de vista**). Use `description_full` só para fundamentar o que for revelado depois. "
        "Se o JSON trouxer **`revisit`: true**, o jogador **voltou** a um lugar já visitado: **não** "
        "repita a descrição completa nem refaça inventário do cômodo. Com **nada novo** no espaço, "
        "**uma** frase de retorno pode bastar; acrescente só **delta** (o que mudou, o que a intenção "
        "dele altera, luz portátil, som novo). Em ciclos de entra-e-sai entre os mesmos cômodos, "
        "trate como atualização mínima: **não** re-descreva mesa, fogão, escada, cheiro e lista de saídas "
        "a cada volta. Se nada mudou, prefira resposta curta (1 frase, tipicamente até ~160 caracteres), "
        "com estrutura de retorno simples («você volta para X» + no máximo **um** toque ambiental). "
        "Esse toque é **um único detalhe** (ex.: só temperatura **ou** só luz **ou** só som), nunca dois "
        "ou três no mesmo retorno. "
        "**Proibido** em revisit estável: recitar novamente lista de conexões/portas, refazer inventário "
        "de objetos fixos, ou repetir o mesmo bloco de vitral/escada/mesa/fogão já descrito há instantes. "
        "Se algo **salta** agora por causa da ação ou da luz, "
        "descreva **só** isso. Em revisit, evite repetir caminho óbvio no texto e foque no que importa "
        "**neste** turno. Quando o jogador **não mudou de cômodo** entre as suas respostas (só nova "
        "intenção no mesmo lugar), **não** recarregue o cenário inteiro: continue no fio do que já "
        "estava estabelecido.\n\n"
        f"{scene_image_note}\n\n"
        "Use **`roll_dice`** quando uma ação do jogador precise de sorte (teste, disputa, risco, "
        "oposição, **acrobacia ou esforço físico incerto**): envie **`skill`** (texto livre que descreve a "
        "manobra) e **`difficulty`** (`muito_facil`, `facil`, `medio`, `dificil`, `muito_dificil`) coerente "
        "com a dificuldade que você já estabeleceu na cena. A ferramenta devolve falha crítica, falha, "
        "sucesso ou sucesso crítico (sorteio d100). **Chame a tool neste mesmo turno** antes de narrar o "
        "desfecho físico quando o jogador já deu um gesto minimamente concreto (ex.: \"acrobacia simples\", "
        "\"salto até à janela\"). Só responda **sem** `roll_dice` se, objetivamente, faltar um dado "
        "indispensável ao corpo (ex.: direção, alvo) e uma **única** pergunta neutra for inevitável. "
        "Para números em intervalo ou cara/coroa isolados, use as outras ferramentas. Integre qualquer "
        "resultado ao que você narrar em seguida. Em **falha** de busca ampla ou de percepção, aplica a "
        "regra **«`roll_dice` em falha»** acima: **não** confirmes segredos nem eco o `skill`.\n\n"
        "**Fadiga perceptível na prosa:** só descreva cansaço físico quando houve esforço realmente "
        "relevante na ficção (corrida, luta, salto, escalada, carga pesada por tempo, posição muito "
        "incômoda por período, **ou comer demais** já concretizado na narração: sensação de peso, "
        "arrepio de digestão, falta de fôlego ao mover-se depressa, vontade de parar). Deslocamentos "
        "curtos entre cômodos e ações triviais **não** devem gerar frases de exaustão.\n\n"
        "**Dificuldade para percepção/investigação (seguir sugestão):** use `muito_facil`/`facil` apenas "
        "quando a ação for **muito específica** e o alvo estiver próximo/atingível; `medio` para varredura "
        "focada com incerteza real; `dificil` quando houver pouco tempo, baixa luz, ruído, distração, "
        "obstruções ou pista muito sutil; `muito_dificil` para pistas mínimas em cenário hostil. "
        "«Vasculhar tudo» ou vários barris/armários de uma vez: **no mínimo** `medio`, mesmo que o texto "
        "do `skill` cite uma suspeita do jogador. Se a ação for direta no ponto certo, você pode resolver "
        "sem teste.\n\n"
        "**`difficulty` em `roll_dice` (obrigatório ser honesto com o risco):** `muito_facil` e "
        "`facil` são só para gestos **objetivamente triviais** no contexto (passo curto, apoio sólido, "
        "quase zero risco de queda feia). **Nunca** use `facil` nem `muito_facil` para **giro mortal**, "
        "**mortal para trás**, **salto com rotação completa**, **voltas no ar**, equilíbrio arriscado em "
        "móveis ou chão irregular com pressão (furtividade, pressa, feridas leves) - isso é no mínimo "
        "**`medio`**, e em ambiente hostil ou fadiga já ruim no ENGINE_CONTEXT sobe para **`dificil`** ou "
        "**`muito_dificil`**. `medio`: atlético sério, risco moderado (cambalhota exigente, salto com "
        "pouso apertado). `dificil`: mortal ou equivalente, precisão alta, ou corpo já cansado. "
        "`muito_dificil`: perigo extremo, exaustão forte, ou superfície/armadilha que torna a manobra "
        "quase suicida.\n\n"
    )
