from app.config import NarratorPromptConfig
from app.narrator_prompt.section_scene_image_note import scene_image_instruction_paragraph
from tools.move import STARTING_PLACE_NAME


def tools_move_section_body(config: NarratorPromptConfig) -> str:
    scene_image_note = scene_image_instruction_paragraph(config)
    return (
        "Use **`move`** quando o jogador **for para outro lugar** do mapa (não para o lugar inicial "
        f"**{STARTING_PLACE_NAME}** enquanto ele não tiver saído dele): em `place_name` use o **nome "
        "canônico** do mapa. O jogador fala em linguagem natural («volto pro salão grande», «sala principal»): "
        "**você** traduz para o nome certo (ex.: **São Principal**) antes de chamar a tool; não exija que "
        "ele copie o dicionário.\n\n"
        "Ao narrar a **chegada** quando **`revisit`: false**, baseie-se **apenas** em **`basic_description`** "
        "e em `player_facing_summary` **e** nas **conexões** retornadas (objetos com `to`, `how` e "
        "sinalizadores de passagem). **Não** puxe para a prosa de chegada o que seria só da camada "
        "**`details`** (ainda não está no JSON). Com **`revisit`: true**, se vier **`details`**, pode "
        "aprofundar; em prosa, priorize o "
        "que é perceptível por `how` (porta, janela, vão, escada, treliça, etc.) como **âncoras "
        "espaciais**; não transforme em lista técnica. Trate `to` como referência de motor, não como "
        "fala obrigatória ao jogador, **mas** na chegada a um cômodo novo cite de forma natural "
        "**as saídas visíveis principais** (portas e passagens realmente transitáveis no `move`) para "
        "orientação do jogador. Quando houver 5 ou menos saídas visíveis, mencione todas "
        "mais imediatas no texto da chegada; se houver nomes canônicos claros (ex.: Despensa, São "
        "Principal), pode citar esses destinos junto com o `how` em linguagem diegética. Se o acesso "
        "parecer oculto/segredo ou não diretamente visível, "
        "não revele o destino nominal antes de exploração pertinente. Se a conexão sugerir obstáculo "
        "(ex.: `seems_traversable_now=false`, treliça sem passagem, janela só para ver), trate como "
        "**secundário** na lista mental do personagem: **não** equacione com porta ou passagem principal; "
        "pode ser um vão de luz ou vista, sem virar «via» como as saídas de fato. Descreva a limitação "
        "e **não valide deslocamento** por aí sem ação clara. Ao voltar texto do mapa em narração, **filtre** "
        "julgamentos de tesouro/valor ou ausências categóricas para a **voz do personagem** (ver "
        "**Regra dura de anti-vazamento na chegada:** em resposta de `move` (entrada em cômodo), "
        "**proibido** mencionar «abertura secreta», «passagem oculta/discreta», «quase imperceptível», "
        "«fenda estranha», «ventilação suspeita» ou qualquer formulação equivalente que sugira caminho "
        "escondido. Se não houve gatilho válido (ação direta no ponto certo ou `roll_dice` bem-sucedido), "
        "essas informações **não existem** na narração desse turno. "
        f"**Ponto de vista**). Use `description_full` só para fundamentar o que for revelado depois. "
        "Se o JSON trouxer **`revisit`: true**, o jogador **voltou** a um lugar já visitado: **não** "
        "repita a descrição completa nem refaça inventário do cômodo. Com **nada novo** no espaço, "
        "**uma** frase de retorno pode bastar; acrescente só **delta** (o que mudou, o que a intenção "
        "dele altera, luz portátil, som novo). Em ciclos de entra-e-sai entre os mesmos cômodos, "
        "trate como atualização mínima: **não** re-descreva mesa, fogão, escada, cheiro e lista de saídas "
        "a cada volta. Se nada mudou, prefira resposta curta (1 frase, tipicamente até ~160 caracteres), "
        "com estrutura de retorno simples («você volta para X» + no máximo **um** toque ambiental). "
        "Esse toque é **um único detalhe** (ex.: só temperatura **ou** só luz **ou** só som), nunca dois "
        "ou três no mesmo retorno. "
        "**Proibido** em revisit estável: recitar novamente lista de conexões/portas, refazer inventário "
        "de objetos fixos, ou repetir o mesmo bloco de vitral/escada/mesa/fogão já descrito há instantes. "
        "Se algo **salta** agora por causa da ação ou da luz, "
        "descreva **só** isso. Em revisit, evite repetir caminho óbvio no texto e foque no que importa "
        "**neste** turno. Quando o jogador **não mudou de cômodo** entre as suas respostas (só nova "
        "intenção no mesmo lugar), **não** recarregue o cenário inteiro: continue no fio do que já "
        f"estava estabelecido.\n\n"
        f"{scene_image_note}\n\n"
    )
